# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Documentation
    url: docs/
    weight: 20
  - name: Blog
    url: blog/
    weight: 30
  - name: Topics
    url: tags/
    weight: 40
  # - name: Showcase
  #   url: showcase/
  #   weight: 40
  #   weight: 50

sidebar:
  - identifier: more
    name: Still need help?
    params:
      type: separator
    weight: 1
  # - identifier: community
  #   name: "Community"
  #   pageRef: "/community"
  #   weight: 2
  - identifier: github
    name: "Github Issue ↗"
    url: "https://github.com/ysyyhhh"
    weight: 3
